# Generated by Django 5.2.17 on 2026-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
